language:
  - swift

os:
  - osx

osx_image:
  - xcode12.2

script:
  - xcodebuild build -project MeasuringCompileTimeExample.xcodeproj -scheme MeasuringCompileTimeExample -destination "platform=iOS Simulator,name=iPhone 12"
