os:
  - osx

osx_image:
  - xcode10.1

script:
  - xcodebuild test -project MeasuringCompileTimeExample.xcodeproj -scheme MeasuringCompileTimeExample -destination "platform=iOS Simulator,name=iPhone XS"
